#!/usr/bin/env python3
"""Regenerate docs/regenerative-geometry.md from the design file.

    python3 scripts/qa/regen/fig/report.py ~/Downloads/"CVR Regen Page.fig" \
        > docs/regenerative-geometry.md

Needs the decoded document alongside it; decode.py writes doc.bin/schema.json
into this directory on its first run.
"""
import os, sys, subprocess
HERE = os.path.dirname(os.path.abspath(__file__))

if not os.path.exists(os.path.join(HERE, 'doc.bin')):
    fig = sys.argv[1] if len(sys.argv) > 1 else None
    if not fig:
        sys.exit("doc.bin missing; pass the .fig path so it can be decoded")
    subprocess.run([sys.executable, os.path.join(HERE, 'decode.py'), os.path.expanduser(fig)],
                   check=True, stdout=subprocess.DEVNULL)

sys.path.insert(0, HERE)
exec(open(os.path.join(HERE, 'sections.py')).read())

L = all_leaves()
print("# Regenerative design geometry\n")
print("Generated by `scripts/qa/regen/fig/report.py` from the client's `.fig`.")
print("Do not hand-edit; re-run the script instead.\n")
print(f"Artboard **{ABW:.0f} x {ABH:.0f}**. All raw numbers are design pixels.\n")
for y0, y1, label in SEAMS:
    BH = y1 - y0
    mine = [r for r in L if in_band(r, y0, y1)]
    print(f"\n## {label}\n")
    print(f"Band y {y0:.0f}..{y1:.0f}, height **{BH:.0f}** (artboard/band aspect {ABW/BH:.3f}).")
    print(f"Share of artboard: top {100*y0/ABH:.2f}%, height {100*BH/ABH:.2f}%.\n")
    print("| layer | type | x | y | w | h | x% | w% | top% | h% |")
    print("|---|---|--:|--:|--:|--:|--:|--:|--:|--:|")
    for r in mine:
        print(f"| {r['name'][:38]} | {r['type']} | {r['x']:.0f} | {r['y']:.0f} | {r['w']:.0f} | {r['h']:.0f} "
              f"| {100*r['x']/ABW:.2f} | {100*r['w']/ABW:.2f} | {100*(r['y']-y0)/BH:.2f} | {100*r['h']/BH:.2f} |")
